# frozen_string_literal: true

plugins:
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-minitest: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Include:
    - "**/*.rb"
    - "**/*.gemspec"
    - "**/Gemfile"
    - "**/Rakefile"
    - Gemfile.lint

# Layout
Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
